### ISSUE TITLE
Huge Fee for creating reveiver. 

### ISSUE THREAD

**Issue by sam1690** [Meshugah/ERC20-CommonGasWallet#2]
HI,

I was in impression that create receiver txn will treat as a simple txn and fee also charges as a simple txn but i am gettig charges around $140 for on receiver. How can i pay this much amount for all my user's wallet just fo create their wallet.  Is there any way, by which we can reduce create receiver txn fee charges. 

Please help me, i have followed your tutorial. Now i am stuck here.  I am really appreciate your help. 

Thanks

**Comment by pawanlapits** [comment]
I  am also facing same issue. I have tried alot but did not find any solution.

**Comment by Meshugah** [comment]
Hey guys. Sorry for the delay. It's a cost that comes with the design choice. It was worthwhile for us as to use it because it outweighed the costs of using an insured wallet provider that was charging per transaction. This acted as a middle-layer wallet structure.
